version: "3"
services:
  openproject:
    image: openproject/community:8
    ports:
      - "8080:80"
    environment:
      - SECRET_KEY_BASE=secret
    volumes:
      - /var/lib/openproject/pgdata:/var/openproject/pgdata
      - /var/lib/openproject/static:/var/openproject/assets
      